### ISSUE TITLE
Lambda invvocation error

### ISSUE THREAD

**Issue by Vikulguptas** [dmhacker/alexa-youtube-skill#10]
START RequestId: ce61e347-8532-11e7-98d6-013b034f9a64 Version: $LATEST
Unable to import module 'index': Error
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

When I try to use the skill after following ur instructions i get the above error .

**Comment by dmhacker** [comment]
Are you using the correct zip file? And what is your Node version?

**Comment by Vikulguptas** [comment]
I downloaded the file from the github https://codeload.github.com/dmhacker/alexa-youtube-skill/zip/master

**Comment by dmhacker** [comment]
Ah, the file you are uploading is actually nested. Try using this link: https://github.com/dmhacker/alexa-youtube-skill/blob/master/alexa-youtube-skill.zip?raw=true

**Comment by Vikulguptas** [comment]
let me try that and get back to you .

**Comment by Vikulguptas** [comment]
works now. It has glitches like when i ask it to search youtube for despactio, it doesn;t do anything and comesout. Prince works , and other songs work too

**Comment by Vikulguptas** [comment]
Thanks dmhacker.

**Comment by dmhacker** [comment]
No problem! That's strange with Despacito because I just tried it on my machine and it worked ... maybe refine your query? Anyway, glad it works now. :) Always happy to help.
