### ISSUE TITLE
Audio only : feature request.

### ISSUE THREAD

**Issue by greg12579** [dmhacker/alexa-youtube-skill#17]
There appears to be a way to get audio only based on this https://market.mashape.com/ehmo/savedeo.
Would be nice to take advantage of that as it would reduce the amount of bandwidth.

**Comment by dmhacker** [comment]
Thanks! I'll consider integrating this in.

**Comment by dmhacker** [comment]
Redirecting comments for this to #11 since it's related to speeding up video/audio playback.
