### ISSUE TITLE
Could not find any linked video skills

### ISSUE THREAD

**Issue by jimkar** [dmhacker/alexa-youtube-skill#18]
I did all the steps and although on the test page on my developer account the response is correct, on my alexa device I get this message "I Could not find any linked video skills"... What is going wrong?

**Comment by yoedba** [comment]
I get the same problem

**Comment by yoedba** [comment]
I asked alexa to search for penny lane by the beatles, here is what i got:
START RequestId: a7b70809-e348-11e7-b191-87fefe30da08 Version: $LATEST
16:38:05
2017-12-17T16:38:05.064Z	a7b70809-e348-11e7-b191-87fefe30da08	Searching ... lane by the Beatles
16:38:05
2017-12-17T16:38:05.623Z	a7b70809-e348-11e7-b191-87fefe30da08	SyntaxError: Unexpected token C at Object.parse (native) at Request._callback (/var/task/index.js:84:29) at Request.self.callback (/var/task/node_modules/request/request.js:188:22) at emitTwo (events.js:87:13) at Request.emit (events.js:172:7) at Request.<anonymous> (/var/task/node_modules/request/request.js:1171
16:38:05
END RequestId: a7b70809-e348-11e7-b191-87fefe30da08
16:38:05
REPORT RequestId: a7b70809-e348-11e7-b191-87fefe30da08	Duration: 784.91 ms	Billed Duration: 800 ms Memory Size: 128 MB	Max Memory Used: 48 MB
16:38:05
RequestId: a7b70809-e348-11e7-b191-87fefe30da08 Process exited before completing request

**Comment by fretes1** [comment]
@jimkar , @yoedba 

Hello, I had the same issue...

It was the language for me, My alexa is in English UK, and I created (Amazon Developer) the skill in English.

**Comment by dmhacker** [comment]
This is strange. In your Lambda servers, do you have the Node.js version set to 6.1.0? Do you also have the correct zip file uploaded (see README)?

**Comment by JuanRdBO** [comment]
Hello I had the same problem. I changed it to English (U.K) but it did not change the behavior. Any thoughts?

**Comment by dmhacker** [comment]
@jimkar @yoedba @fretes1 @JuanRdBO 

Did any of you get the skill working properly?

**Comment by dmhacker** [comment]
Stale issue. Closing.
