### ISSUE TITLE
Request: Heroku support

### ISSUE THREAD

**Issue by drizzt09** [dmhacker/alexa-youtube-skill#19]
I got the kodi skill working with using the Heroku setup option from https://github.com/m0ngr31/kodi-alexa
because I couldnt get the AWS version setup (no Credit Card)

**Comment by dmhacker** [comment]
This skill works by linking a Heroku server with an AWS Lambda server running this code. The skill defaults to using my Heroku server, but you can always set your own up here by following the instructions @ https://github.com/dmhacker/dmhacker-youtube.

**Comment by dmhacker** [comment]
Moving this to #11.
