### ISSUE TITLE
Problems with Install Step 6

### ISSUE THREAD

**Issue by Novo** [dmhacker/alexa-youtube-skill#22]
Configuration page: under Endpoint, select AWS ...
What should I put in the blank after Default: ?
Error: Please select a default endpoint.

**Comment by rosschang** [comment]
Having the same issue. Tried entering a name of more than 25 character long and got a different error message: 

Error: Invalid ARN for NA region. Please provide a valid ARN in the form 'arn:aws:lambda:us-east-1:000000000000:function:myFunction:myFunctionVersion'

Help...

**Comment by EGregg** [comment]
I'm stuck at this step as well

**Comment by dmhacker** [comment]
In the blank spot, you will be putting in the ARN of the Lambda server that will be running your skill. See the top right of this image. 
![capture](https://user-images.githubusercontent.com/3221148/35189330-f033e1d4-fdfc-11e7-8621-0ce6c6210561.PNG)
If you haven't made your Lambda server yet, do that first and then add its ARN to the blank field.
