### ISSUE TITLE
The skill swallows words

### ISSUE THREAD

**Issue by xPumaa** [dmhacker/alexa-youtube-skill#24]
Hey,

Alexa recognises all the words but not all the words arrive at the skill.
The words have either disappeared at the front, back or on both sides.

**Comment by dmhacker** [comment]
What exactly do you mean by this? Is this skill not recognizing what words you are giving it?

**Comment by xPumaa** [comment]
Alexa recognizes all words, but not the skill. The skill cuts off spoken words that are either front, back or front and back.

**Comment by dmhacker** [comment]
Could you give me an example? Like if you said "Alexa, ask YouTube to play ...", is it just not calling the skill? Or is the "..." not being recognized by the skill?

**Comment by xPumaa** [comment]
I ask "Alexa, ask YouTube to play Nightcore be what you wanna b", but the skill recognizes the words "be what you wanna be" and cuts off the word nightcore. Now when I look at what Alexa has understood, I see the full text "Alexa, ask YouTube to play Nightcore be what you wanna b". What Alexa understands is not consistent with what the skill understands.

**Comment by dmhacker** [comment]
Otherwise is it playing videos correctly? I'll look into this by testing on my account.

**Comment by xPumaa** [comment]
If I ask "Alexa, ask YouTube to play Nightcore nightcore be what you wanna b" then the Skill recognizes "nightcore be what you wanna be"

**Comment by dmhacker** [comment]
That's strange. It might be an issue with your Alexa device. I gave my skill your phrase and it came up (correctly) with this and with no words omitted:

![image](https://user-images.githubusercontent.com/3221148/35250113-d947ccfe-ff89-11e7-840e-f2c37b93e778.png)

**Comment by dmhacker** [comment]
Maybe try using "search for" instead of "play"?

**Comment by xPumaa** [comment]
I am using the German version of the Sample Utterances

**Comment by dmhacker** [comment]
I don't think you need to. Did you try a different phrase?

**Comment by dmhacker** [comment]
Stale issue. Closing.
