### ISSUE TITLE
Could not extract signature deciphering actions

### ISSUE THREAD

**Issue by srinivas81** [dmhacker/alexa-youtube-skill#27]
Since few days, I have been getting the message on alexa as "there is a problem with the requested skills response".  When I tried your web URL for your heroku server, and I search under "Youtube Search"  , I see this error: "Could not extract signature deciphering actions". Any idea whats going on?

**Comment by sam170582** [comment]
I have the same issue

**Comment by dmhacker** [comment]
Seems like @sam170582 provided a good fix. Keep in mind that ytdl-core has been updated to 0.20.1 in the latest release. Closing the issue.
