### ISSUE TITLE
There was a problem with the requested skills response.

### ISSUE THREAD

**Issue by BooleeTR** [dmhacker/alexa-youtube-skill#30]
I set up everything as noted. Seemed pretty straight forward. However I get this response from alexa when trying the skill "There was a problem with the requested skills response." Please Help.

**Comment by dmhacker** [comment]
Are you still getting this error? Did you specify the correct ARN/upload the correct ZIP file?

**Comment by samay-sharma** [comment]
I am also running into the same issue. I verified that my ARN is correct and ZIP file is uploaded. I'm pasting the response json string below. It looks like it is able to find the right video and converts it into its audio form, but still gives an error message "There was a problem with the requested skill's response".

```
{
	"body": {
		"version": "1.0",
		"response": {
			"outputSpeech": {
				"type": "SSML",
				"ssml": "<speak>I am now playing Ed Sheeran - Shape of You [Official Video].</speak>"
			},
			"card": {
				"type": "Simple",
				"title": "Search for \"shape of you\"",
				"content": "Alexa found \"Ed Sheeran - Shape of You [Official Video]\" at https://www.youtube.com/watch?v=JGwWNGJdvx8."
			},
			"directives": [
				{
					"type": "AudioPlayer.Play",
					"playBehavior": "REPLACE_ALL",
					"audioItem": {
						"stream": {
							"token": ...,
							"url": "https://dmhacker-youtube.herokuapp.com/site/JGwWNGJdvx8.m4a",
							"offsetInMilliseconds": 0
						}
					}
				}
			],
			"shouldEndSession": true
		},
		"sessionAttributes": {}
	}
}
```

**Comment by BooleeTR** [comment]
I verified the ARN and uploaded the correct zip file. Im fairly new to
tweaking with alexa skills, so if you need any other information from me id
be happy to help. I appreciate you looking into it.

**Comment by dmhacker** [comment]
@BooleeTR 

Can you try querying the skill for help? Try asking "Alexa, ask YouTube for help." Let me know what it says.

**Comment by fairytalenightmare** [comment]
@dmhacker This is what i am now having trouble with, she says basically the same thing, i asked Alexa, ask youtube for help.... and it said the same thing

**Comment by dmhacker** [comment]
@fairytalenightmare Are you using the correct ZIP file?

**Comment by fairytalenightmare** [comment]
@dmhacker I used the zip file you linked to in your latest walkthrough with the screen caps you posted a couple of days ago.

**Comment by BooleeTR** [comment]
I asked "Alexa, ask YouTube for help." She recognizes what I'm saying but
then just deactivates without saying anything. Also what do you mean by
querying the skill for help? Forgive me I'm new to alexa skills.

**Comment by gigio68** [comment]
The skill worked in quite a few cases. I had a lot of communicating errors with the skills. Some of the songs which the skill recognised were pulled from youtube. However in a couple of occasions I could not stop the song (saying "Alexa stop" resulted in an error and the song carried on playing after the error). Could it be that the setup in the lambda function needs more memory or different settings for the timeout of the basic settings? It is a good start, but the way it is right now can only be annoying, but I am sure with a few tweaks it can be a pretty decent "free" alexa-skill.

**Comment by marlon1144** [comment]
Hi guys,
I got the same problem with my skill now. Everything worked well for over a year and I never had to tweak anything but for some reason it stopped working now. Occassionally it would play a song once a day maybe. Otherwise everytime I ask alexa to play , its says There was a problem with the requested skill response. Can you help please?

**Comment by dmhacker** [comment]
I'm going to merge this into #68 since it seems to be same issue.
