### ISSUE TITLE
Total Noob

### ISSUE THREAD

**Issue by scomay** [dmhacker/alexa-youtube-skill#32]
Hi -- I am trying to create this skill as outlined, however, the steps listed on the Wiki and Amazon's interface are completely different.  

For instance, I never found "Global Fields section, mark that the skill uses audio player directives" where I named Invocation (also, invocation needs to be two words, not one?  "you tube"  not "youtube"?  I did find, under Interfaces, a tab to turn on Audio Player -- is that correct?

In the Interaction Model page, I found build-in Intents and create a Custom Intent, but no "Schema Intent".  And when I tried to Create an Intent and name it Schema, pasting in the script 
{
  "intents": [
    {
      "slots": [
        {
          "name": "VideoQuery",
          "type": "VIDEOS" ...etc...

I got a dialogue box requesting I "Select an Existing Slot" and that there were "no existing slots" and the box changed name to "Sample Utterances" so I deleted the first script and pasted in Sample Utterances from the Wiki, but that wasn't supported, either...

Is there an easier to follow set of instructions is this skill just not meant for noobs like myself.  I was really hoping this would work as my teenage son loves listening to youTube while he falls asleep.

**Comment by dmhacker** [comment]
I will work on getting a more complete guide up over the next few days. My schedule's been pretty packed lately because I just got back to university after spring break, but I'll do my best.

**Comment by fairytalenightmare** [comment]
I was thinking the same thing, really hope to see the update soon. x

**Comment by scomay** [comment]
thanks dmhacker -- that would be awesome!  which university are you going to?

**Comment by el-lsan** [comment]
I'm facing the same issue 🤦‍♂️ ! Not sure if the wiki is outdated or i'm a retard 😒

**Comment by dmhacker** [comment]
@scomay I'm attending UCSD! Studying towards a B.S. in computer science :)

@fairytalenightmare @el-lsan I'll have the updates done by tonight. Seems like Amazon updated their developer page. Just hang tight for now.

**Comment by scomay** [comment]
oh, sweet!  I'm a Banana Slug myself.  I live up in Seattle now...which is Amazonia these days.

**Comment by scomay** [comment]
good luck with your degree, by the way...look into video games when you are done.  good money, lots of jobs, great culture.

**Comment by dmhacker** [comment]
@scomay Tritons unfortunately :P But yes, I will certainly look into the field.

**Update:** Please see [this link](https://github.com/dmhacker/alexa-youtube-skill/wiki/Setup-Process-%28Current%29) for a revised setup process. Let me know if anything's not clear or any other issues arise.

**Comment by fairytalenightmare** [comment]
@dmhacker Thank you so much, unfortunately, I came into an issue at the point where you upload the zip file, i am on a Mac, recompressed the file and it gives me this "The file index.js could not be found. Make sure your handler upholds the format: file-name.method."

**Comment by fairytalenightmare** [comment]
@scomay  any luck? x

**Comment by fairytalenightmare** [comment]
@dmhacker It isnt working. x

**Comment by scomay** [comment]
Haven’t had a chance to try yet, was out sick since last Friday and missed your emails …til now!  But am anxious to give it a shot – thanks!

**Comment by badbob001** [comment]
The revised instructions work! Thanks! Before I could get 'test' to work, I had to first go to the build section and make sure everything under 'skill builder checklist' was green. For me, 'build a model' was not green and I had to click it first.

I also could use lambda_basic_execution for the role name as it was also used by another function, so I simple used lambda_basic_execution_youtube.

**Comment by dmhacker** [comment]
Excellent, glad to hear that. I'll make sure to update the build process to emphasize that. Closing this issue.
