### ISSUE TITLE
IT's Work but i'm waiting very long

### ISSUE THREAD

**Issue by taranezy** [dmhacker/alexa-youtube-skill#33]
I am waiting to alexa play music over 1 min, 2,3 min sometimes, is it normal for this skill, or you don't wait so long for loading ? 

Some sugetistion what i can do for faster loading of song, i try with default dmhacker and with my own but its same problem.

**Comment by dmhacker** [comment]
Unfortunately, yes, because the library I'm using does some post-processing to the audio stream to make it conform to Alexa's supported bitrate formats. I'm working on improving it later though.

Try using a shorter video for now if download times are bothersome. Sorry about this!

**Comment by taranezy** [comment]
oke tnx on answer, keep a good work
