### ISSUE TITLE
FTP/tinyurl is invalid - no ZIP file

### ISSUE THREAD

**Issue by aldini10** [dmhacker/alexa-youtube-skill#34]
The Code at http://viahold.com/31Kq.
or http://viahold.com/31Kq
will not download and is invalid on firefox/IE/Chrome - no proxy settings or firewall
I can nslookup viahold.com
Did you move the ZIP file?
Is it on a public ftp site

**Comment by fairytalenightmare** [comment]
I used Safari with no issues, try that.

**Comment by dmhacker** [comment]
Strange, it seems to be working fine for me, and I tested it on Firefox/Chrome. Try the direct link too: https://github.com/dmhacker/alexa-youtube-skill/blob/master/build/alexa-youtube-skill.zip?raw=true

**Comment by dmhacker** [comment]
Closing because both download links have been provided and appear to be working.
