### ISSUE TITLE
How to make it work on a french echo ?

### ISSUE THREAD

**Issue by MisterSeb** [dmhacker/alexa-youtube-skill#39]
Hi, I followed this great topic, thanks.
But it is not working for me. Maybe I missed something, or is it linked to the language of my french echo.
How can I make a french interaction model ?
Where are listed the vocal commands we can use ?
Is there a lsit of checks I can validate ?
Thanks again.
MisterSeb

**Comment by dmhacker** [comment]
French is not supported yet for this skill.
