### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Firni95** [dmhacker/alexa-youtube-skill#4]
When asking alexa to open the skill there is an error "The target Lambda application returned a failure response".

When checking Lambda there is "This function contains external libraries. Uploading a new file will override these libraries."

Do I have to buy a better/larger version of amazon aws?

Thank you!

**Comment by Firni95** [comment]
Btw: Your zip.py has a problem with the print "Done" line... jfyi

**Comment by Firni95** [comment]
Log-Export:

REPORT RequestId: 84aa8649-6664-11e7-bab3-ab117900dc60	Duration: 1.05 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 24 MB

**Comment by angelos1989** [comment]
I have the same issue:

`Unable to import module 'index': Error
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/index.js:1:75)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)`

**Comment by dmhacker** [comment]
You shouldn't have to upgrade Lambda at all, and I'll update the zip.py file to be compatible with Python 3 (I was using Python 2.7, which is why the "Done" line isn't working). Otherwise, I'm going close this and redirect your comments to https://github.com/dmhacker/alexa-youtube-skill/issues/2.
