### ISSUE TITLE
Are you hiding the instructions on purpose?

### ISSUE THREAD

**Issue by famewolf** [dmhacker/alexa-youtube-skill#43]
Your Readme states :  "The instructions have been moved to this repository's wiki page."  which takes you to  https://github.com/dmhacker/alexa-youtube-skill/wiki  which then states:  "For instructions on how to setup the skill, please visit the Setup Process page. " which takes you to https://github.com/dmhacker/alexa-youtube-skill/wiki/Setup-Process-%28Current%29 which says:  "For now, the setup process is detailed here. The guide will be moved back to the wiki shortly." and this link https://imgur.com/a/H5R7L points to a single screenshot that is totally worthless.  This is dated April 5th so I can't be the first person to encounter this mess.

**Comment by KirovAir** [comment]
There are multiple screenshots which will guide you just fine.

**Comment by famewolf** [comment]
Thank you. I clicked on the big blue arrow saying "next post" that obviously was the wrong thing to do.
