### ISSUE TITLE
Latest ZIP doesn't contain alexa node_modules

### ISSUE THREAD

**Issue by Karch22** [dmhacker/alexa-youtube-skill#50]
Hi. I have done the installation described in the https://imgur.com/a/H5R7L.
Its not working, ALEXA said: "there is an issue by the requested skill"

I guess the issue comes from the latest Zip File as there is no folder "node_modules" and the filesize is only 11kb.

THX in advance

**Comment by Karch22** [comment]
![grafik](https://user-images.githubusercontent.com/43779259/46392967-91281880-c6e3-11e8-80c2-9328715c00a7.png)

**Comment by Karch22** [comment]
![grafik](https://user-images.githubusercontent.com/43779259/46393031-d3515a00-c6e3-11e8-9f85-9648c7cf1830.png)

**Comment by Karch22** [comment]
sorry, i closed it wrongly.

**Comment by dmhacker** [comment]
Thanks. Just fixed it.
