### ISSUE TITLE
Can't find the zip. file for the upload later on in AWS. Can anybody help?

### ISSUE THREAD

**Issue by Kalle710** [dmhacker/alexa-youtube-skill#55]
See below a screenshot out of the Youtube Tutorial. It shows the content of the folder from Github.

<img width="575" alt="bildschirmfoto 2018-12-11 um 18 29 12" src="https://user-images.githubusercontent.com/45772414/49818658-9654b400-fd73-11e8-99d1-799e81584089.png">

**Comment by tal9000v2** [comment]
If you are following the instructions, located here : https://imgur.com/a/H5R7L

"To do that, select Code entity type to "Upload a .ZIP file" and click on the Upload button. You will need to have downloaded the ZIP file from this link: https://github.com/dmhacker/alexa-youtube-skill/releases/latest"

Visit that link and you can download the zip file to load into your Lambda function

**Comment by dmhacker** [comment]
@tal9000v2 has already provided the relevant links. Here is [a direct link](https://github.com/dmhacker/alexa-youtube-skill/releases/download/3.0.0/alexa-youtube-skill.zip) to the most recent ZIP file;
