### ISSUE TITLE
I already have a role called "lambda_basic_execution"

### ISSUE THREAD

**Issue by dvdchance** [dmhacker/alexa-youtube-skill#57]
When creating the skill, I get error that I already have lambda_basic_execution. I changed name to lambda_basic_execution2, but naturally the skill doesn't work. It takes my query but I get no response back.

Any suggestions? I'm assuming I created the first lambda_basic_execution  when I created the google assistant skill.

**Comment by MarkLurie90** [comment]
Hi, Same problem, can someone please assist?

**Comment by dmhacker** [comment]
Please see the latest iteration of the setup guide. It will walk you through what permission(s) you need to enable during creation of a new role. You can name the role whatever you wish.
