### ISSUE TITLE
How to activate skill in the app?

### ISSUE THREAD

**Issue by sledgehammer123** [dmhacker/alexa-youtube-skill#58]
Hello,
the skill works well for me in the test area. I can see it under developer in the app. But i can´t see it in the app under "video" settings. Alexa: "Can´t find any video skills."
Thank you for help.
Sledge

**Comment by dmhacker** [comment]
I'm not sure it will appear under video skills. You can query it by saying: "Alexa, ask YouTube to play ..." (replace the ellipses with with the title of the video you want to search).
