### ISSUE TITLE
Alexa suddenly stoped playing live video

### ISSUE THREAD

**Issue by ThatOneCalculator** [dmhacker/alexa-youtube-skill#60]
It worked before, but about a week ago stopped working, and now when asked to play a live video, returns the standard "there was a problem with the requested skill's response".

**Comment by Manav-Seth** [comment]
I am having the same issue,

**Comment by Manav-Seth** [comment]
I rolled back the lambda function and 2.0.7 does work.

**Comment by dmhacker** [comment]
Try re-deploying with the new setup guide and latest version (3.0.5)? If it still doesn't work, can you provide me with CloudWatch logs from your Lambda function?

**Comment by dmhacker** [comment]
I'm going to merge this into #68 since it seems to be same issue.
