### ISSUE TITLE
There is no blueprint template for alexa.

### ISSUE THREAD

**Issue by andreabac3** [dmhacker/alexa-youtube-skill#63]
The following stage has removed by AWS: "Select the Blueprints section and then use alexa-skills-kit-color-expert as the blueprint. It might help to type in "alexa" into the Blueprints search bar to narrow your results."
There is no blueprint template for alexa.

**Comment by zkyenet** [comment]
Having the same issue.

**Comment by PhuongDinh129** [comment]
same problem

**Comment by Alex-Graham** [comment]
Under the serverless option. I have found the alexa skill set

**Comment by steve3p0** [comment]
Alex-Graham, OK.  So then what?  If you select "Browse serverless app repository" and then "alexa-skills-kit-color-expert, what do you do next?  It takes you to "Review Configure and Deploy", where all I can do is name the skill and enter a TopicNameParameter.  I can't follow the rest of the instructions at https://imgur.com/a/H5R7L/.  There is a "Copy as SAM Resource" near the top of the page, but I am lost as what to do next.

**Comment by steve3p0** [comment]
> Under the serverless option. I have found the alexa skill set

Alex-Graham, OK.  So then what?  If you select "Browse serverless app repository" and then "alexa-skills-kit-color-expert, what do you do next?  It takes you to "Review Configure and Deploy", where all I can do is name the skill and enter a TopicNameParameter.  I have no idea what I should do with TopicNameParameter, but it's required. At this point, I am prevented from following the rest of the instructions at https://imgur.com/a/H5R7L/.  There is a "Copy as SAM Resource" near the top of the page, but I am lost as what to do next.

**Comment by andrembezerra** [comment]
Here too. Does anyone knows how to setup using serverless app repository?

**Comment by dmhacker** [comment]
Fixed with the latest iteration of the setup guide. :) You won't need the blueprint/serverless app repository option for this to work.

Please see: https://imgur.com/a/H5R7L
