### ISSUE TITLE
Will Using The Skill After 12 Months Cost Money?

### ISSUE THREAD

**Issue by PhuongDinh129** [dmhacker/alexa-youtube-skill#64]
Hello everyone, 
I want to integrate the Youtube playing service to my Alexa Magic Mirror, but AWS Free Tier will expire after 12 months or if I exceed the usage limit. If I keep using my Youtube skill after that 12 months or exceeding my limit, will I get charged by Amazon? I am new to AWS service so I really don't know how it works. 
Thank you.
P.S: I also followed another guide using "arn:aws:lambda:ap-northeast-1:175548706300:function:YouTube" as the Default Region, but after testing a few songs, it keeps saying "This skill is being throttled by Youtube, please try again later." Does anyone know about this?

**Comment by dmhacker** [comment]
https://aws.amazon.com/lambda/pricing/ for AWS pricing.

Not sure about the throttling but YouTube does have limits on their API, so if you are trying to query videos a lot using the same API key, it will fail.
