### ISSUE TITLE
alexa youtube skill is not playing only asking for download , but with error

### ISSUE THREAD

**Issue by karolosz** [dmhacker/alexa-youtube-skill#71]
Hello, i met this trouble
when i asked: "alexa, ask youtube to search for we will rock you" or " alexa, ask youtube to play for we will rock you "
Alexa replay: " found a video called Queen we will Rock You. Would you like me to download it now?"

so there is no music playing, and even if i said to for the alexa replay  " found a video called Queen we will Rock You. Would you like me to download it now?" = yes, she sqid there zas error and it is end, please can you help me?

i followed this https://imgur.com/a/Cz7FTRj
with 
interaction english for developer amazon:
https://github.com/dmhacker/alexa-youtube-skill/wiki/Interaction-Model-(English)

and for the AWS:
releases 3.0.5
https://github.com/dmhacker/alexa-youtube-skill/releases/tag/3.0.5

please can you help me?

**Comment by PaulREE** [comment]
@karolosz I have the same issue. There is an error after I said "Yes" for starting download: "Skill response was marked as failure. Request Identifier ... The target Lambda application returned a failure response" (iOS Alexa App).
By the way the command "Alexa, ask YouTube for help" works properly.

**Comment by dmhacker** [comment]
Please see #69 for an identical issue. See #68 for current issues with the search functionality.
