### ISSUE TITLE
The nodejs4.3 runtime is no longer supported. We recommend that you migrate your functions that use nodejs4.3 to a newer runtime as soon as possible.

### ISSUE THREAD

**Issue by famewolf** [dmhacker/alexa-youtube-skill#77]
I'm attempting to follow the guide here: https://imgur.com/a/Cz7FTRj   to update to the current version.  AWS will not allow me to upload a zip file because it keeps telling me to fix the nodejs first.  I can't find where to change this.  The screenshots are way out of date and the pages don't even look the same.  For example the screenshots show using nodejs6.10 and my understanding is they are at version 12 now with 6.10 deprecated a year ago?

**Comment by Paul-PSDigital** [comment]
Hey, you want to look for node10, perhaps you're confusing node with npm (which is currently at v6)

**Comment by famewolf** [comment]
Thank you...but where do I go from the functions section to change the version of node.js?  

*update* and right after i ask I see it.  Thanks!
