### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by harikiran1985** [dmhacker/alexa-youtube-skill#9]
It takes almost 2-3mins to search for a video in youtube and play.

**Comment by dmhacker** [comment]
For a YouTube video of normal length (3-10 min.), it takes less than a minute for the audio to download and process on the backend server. If it takes any longer than this, the video you downloaded is most likely upwards of 20 minutes. 

Right now, if this happens, you are just going to have to wait for the skill to download, and then refine your query next time. In the future, I plan on adding a dialog, so it searches for a video first and then prompts the user asking if it found the correct one. If the user responds with 'yes,' only then does the skill play the audio.

**Comment by dmhacker** [comment]
Closing this and redirecting to #11.
